[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
surrealdb = "1.2.2"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
